workspace 'VVBaseFoundationDemo'
project 'VVBaseFoundationDemo.xcodeproj'

platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

target :VVBaseFoundationDemo do
    project 'VVBaseFoundationDemo.xcodeproj'
    
    #https://github.com/gaoxiaowei/base
    pod 'VVBaseFoundation', '~> 1.0’

end






